// URDFエクスポータ(企画書§5)。
// リンクフレームは全てworld軸揃え(rest)なので、joint originは平行移動のみ・axisはworld軸のまま。
import { Vector3 } from "three";
import type { Geom } from "../types";
import {
  buildExportData,
  fmt,
  quatToRpy,
  servoEffortNm,
  servoVelocityRadS,
  v3str,
  MM,
  G,
  GMM2,
  type ExpLink,
  type ExportData,
} from "./exportData";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function geomXml(g: Geom): string {
  switch (g.type) {
    case "box":
      return `<box size="${fmt(g.sizeMm[0] * MM)} ${fmt(g.sizeMm[1] * MM)} ${fmt(g.sizeMm[2] * MM)}"/>`;
    case "cylinder":
      return `<cylinder radius="${fmt(g.radiusMm * MM)}" length="${fmt(g.heightMm * MM)}"/>`;
    case "sphere":
      return `<sphere radius="${fmt(g.radiusMm * MM)}"/>`;
    case "triprism":
      // URDFに三角柱プリミティブは無いため箱で近似(重心位置は別途正しい)
      return `<box size="${fmt(g.sideMm * MM)} ${fmt(g.sideMm * MM)} ${fmt(g.thickMm * MM)}"/>`;
  }
}

/** triprismの箱近似は中心がズレるため原点補正 */
function geomOriginOffset(g: Geom): Vector3 {
  if (g.type === "triprism") return new Vector3(g.sideMm / 2, g.sideMm / 2, 0);
  return new Vector3();
}

function linkXml(link: ExpLink, materialSeen: Set<string>, out: string[]): void {
  out.push(`  <link name="${esc(link.name)}">`);
  if (link.massG > 0) {
    const I = link.inertiaGmm2.elements; // 列優先 [xx yx zx xy yy zy xz yz zz]
    out.push(`    <inertial>`);
    out.push(`      <origin xyz="${v3str(link.comMm, MM)}" rpy="0 0 0"/>`);
    out.push(`      <mass value="${fmt(link.massG * G)}"/>`);
    out.push(
      `      <inertia ixx="${fmt(I[0] * GMM2, 9)}" ixy="${fmt(I[3] * GMM2, 9)}" ixz="${fmt(I[6] * GMM2, 9)}" iyy="${fmt(I[4] * GMM2, 9)}" iyz="${fmt(I[7] * GMM2, 9)}" izz="${fmt(I[8] * GMM2, 9)}"/>`
    );
    out.push(`    </inertial>`);
  }
  for (const eg of link.geoms) {
    const rpy = quatToRpy(eg.quat);
    const off = geomOriginOffset(eg.geom).applyQuaternion(eg.quat);
    const pos = eg.posMm.clone().add(off);
    const originAttr = `xyz="${v3str(pos, MM)}" rpy="${fmt(rpy[0])} ${fmt(rpy[1])} ${fmt(rpy[2])}"`;
    const matName = `c${eg.color.replace("#", "")}`;
    out.push(`    <visual>`);
    out.push(`      <origin ${originAttr}/>`);
    out.push(`      <geometry>${geomXml(eg.geom)}</geometry>`);
    out.push(`      <material name="${matName}"/>`);
    out.push(`    </visual>`);
    out.push(`    <collision>`);
    out.push(`      <origin ${originAttr}/>`);
    out.push(`      <geometry>${geomXml(eg.geom)}</geometry>`);
    out.push(`    </collision>`);
    materialSeen.add(eg.color);
  }
  out.push(`  </link>`);
}

export function exportUrdf(data: ExportData): string {
  const { allLinks, allJoints, loopJoints, model } = data;
  const out: string[] = [];
  out.push(`<?xml version="1.0"?>`);
  out.push(`<!-- Generated by Snap Frame Garage -->`);
  out.push(`<robot name="${esc(model.name || "robot")}">`);

  const materialSeen = new Set<string>();
  const linkParts: string[] = [];
  for (const link of allLinks) {
    if (link.massG === 0 && link.geoms.length === 0) continue;
    linkXml(link, materialSeen, linkParts);
  }
  for (const c of materialSeen) {
    const r = parseInt(c.slice(1, 3), 16) / 255;
    const g = parseInt(c.slice(3, 5), 16) / 255;
    const b = parseInt(c.slice(5, 7), 16) / 255;
    out.push(`  <material name="c${c.replace("#", "")}"><color rgba="${fmt(r, 3)} ${fmt(g, 3)} ${fmt(b, 3)} 1"/></material>`);
  }
  out.push(...linkParts);

  for (const j of allJoints) {
    const parent = data.allLinks[j.parentLinkIdx];
    const child = data.allLinks[j.childLinkIdx];
    const originXyz = child.anchorMm.clone().sub(parent.anchorMm);
    const type = j.type === "active" ? (j.continuous ? "continuous" : "revolute") : "revolute";
    out.push(`  <joint name="${esc(j.name)}" type="${type}">`);
    out.push(`    <origin xyz="${v3str(originXyz, MM)}" rpy="0 0 0"/>`);
    out.push(`    <parent link="${esc(parent.name)}"/>`);
    out.push(`    <child link="${esc(child.name)}"/>`);
    out.push(`    <axis xyz="${v3str(j.axis)}"/>`);
    if (j.type === "active" && j.servo && !j.continuous) {
      const range = (j.servo.rangeDeg * Math.PI) / 180;
      out.push(
        `    <limit lower="${fmt(-range)}" upper="${fmt(range)}" effort="${fmt(servoEffortNm(j.servo))}" velocity="${fmt(servoVelocityRadS(j.servo))}"/>`
      );
    } else if (j.type === "active" && j.servo && j.continuous) {
      out.push(`    <limit effort="${fmt(servoEffortNm(j.servo))}" velocity="${fmt(servoVelocityRadS(j.servo))}"/>`);
    } else {
      // 受動関節:駆動力なし(URDFでは表現の限界。effort=0で受動を示す)
      out.push(`    <limit lower="${fmt(-Math.PI)}" upper="${fmt(Math.PI)}" effort="0" velocity="20"/>`);
    }
    out.push(`  </joint>`);
  }

  for (const lj of loopJoints) {
    out.push(
      `  <!-- 閉ループ関節(からくり)はURDFでは表現できないため省略: linkA=${lj.linkA} linkB=${lj.linkB} anchor(mm)=${v3str(lj.anchorMm, 1, 1)} -->`
    );
  }

  out.push(`</robot>`);
  return out.join("\n");
}

export function exportUrdfFromModel(model: Parameters<typeof buildExportData>[0]): string {
  return exportUrdf(buildExportData(model));
}
